# Generated by Django 3.1.14 on 2022-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('mark', models.BooleanField(default=False)),
                ('negative_mark', models.IntegerField(verbose_name=20)),
                ('time', models.IntegerField(verbose_name=20)),
            ],
        ),
    ]
